[package]
name = "serialize_deserialize_bin_tree"
version = "0.1.0"
authors = ["pluoner <jonathan.gerholm@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
